name: CI/CD Frontend Cinephoria

on:
  push:
    branches:
      - main # branche principale de ton front

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # version Node.js pour Vue 3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # crée le dossier dist

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
        run: |
          fly deploy --remote-only --yes
